const types = {
  GET_USERS: 'GET_USERS',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  GET_GROUPS: 'GET_GROUPS',
  UPDATE_PROFILE: "UPDATE_PROFILE"
}

export default types;
