const types ={
    AUTHENTICATE: "AUTHENTICATE",
    GET_USER_FROM_ASYNCSTORAGE_TO_STORE: 'GET_USER_FROM_ASYNCSTORAGE_TO_STORE',
    ADD_ERROR: "ADD_ERROR",
    REMOVE_ERROR: "REMOVE_ERROR"
}

export default types;