const types ={
    AUTHENTICATE: "AUTHENTICATE",
    AUTHENTICATE_SUCCESS: "AUTHENTICATE_SUCCESS",
    AUTHENTICATE_FAILED: "AUTHENTICATE_FAILED",
    GET_USER_FROM_ASYNCSTORAGE_TO_STORE: 'GET_USER_FROM_ASYNCSTORAGE_TO_STORE',
    ADD_ERROR: "ADD_ERROR",
    REMOVE_ERROR: "REMOVE_ERROR",
    LOADING: "LOADING",
    LOADING_SUCCESS: "LOADING_SUCCESS"
}

export default types;