const types = {
  AUTHENTICATE: "AUTHENTICATE",
  AUTHENTICATE_SUCCESS: "AUTHENTICATE_SUCCESS",
  AUTHENTICATE_FAILED: "AUTHENTICATE_FAILED",
  LOGOUT: "LOGOUT",
  GET_AVATAR: "GET_AVATAR",
  UPLOAD_AVATAR: "UPLOAD_AVATAR",
  GET_USER_FROM_ASYNCSTORAGE_TO_STORE: 'GET_USER_FROM_ASYNCSTORAGE_TO_STORE',
  ADD_ERROR: "ADD_ERROR",
  REMOVE_ERROR: "REMOVE_ERROR",
  LOADING: "LOADING",
  LOADING_SUCCESS: "LOADING_SUCCESS",
  TOGGLE_THEME: "TOGGLE_THEME",
  SEND_LEAVE_REQUEST: 'SEND_LEAVE_REQUEST',
  GET_REQUESTS: "GET_REQUESTS",
  LEAVE_REQUEST_SUCCESS: 'LEAVE_REQUEST_SUCCESS',
  CREATE_ATTENDANCE_REQUEST: "CREATE_ATTENDANCE_REQUEST",
  EDIT_REQUEST: "EDIT_REQUEST",
  CANCEL_REQUEST: "CANCEL_REQUEST",
  GET_EVENTS: 'GET_EVENTS',
  GET_HISTORY: 'GET_HISTORY',

  SEND_TRAVEl_REQUEST: 'SEND_TRAVEl_REQUEST',
  TRAVEL_REQUEST_SUCCESS: 'TRAVEL_REQUEST_SUCCESS',
  TRAVEL_REQUEST_FAILED: 'TRAVEL_REQUEST_FAILED',
}

export default types;
