const types = {
    GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
    VUE_NOTIFICATION: "VUE_NOTIFICATION",
    ACCEPT_REQUEST: "ACCEPT_REQUEST",
    REJECT_REQUEST: "REJECT_REQUEST"
}

export default types;
