const types = {
  GET_HOLIDAYS: 'GET_HOLIDAYS',
  ADD_HOLIDAY: 'ADD_HOLIDAY',
  EDIT_HOLIDAY: 'EDIT_HOLIDAY',
  REMOVE_HOLIDAY: 'REMOVE_HOLIDAY',
  ADD_HOLIDAY_SUCCESS: 'ADD_HOLIDAY_SUCCESS',
  ADD_HOLIDAY_FAILED: 'ADD_HOLIDAY_FAILED',

  EDIT_HOLIDAY_SUCCESS: 'EDIT_HOLIDAY_SUCCESS',
  EDIT_HOLIDAY_FAILED: 'EDIT_HOLIDAY_FAILED',

  REMOVE_HOLIDAY_SUCCESS: 'REMOVE_HOLIDAY_SUCCESS',
  REMOVE_HOLIDAY_FAILED: 'REMOVE_HOLIDAY_FAILED',
}

export default types;
