const types = {
    GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
    GET_ATTENDANCES: 'GET_ATTENDANCES',
    GET_GRAPH_DATA: 'GET_GRAPH_DATA',
    GET_STATS: "GET_STATS",
    GET_STATS_SUCCESS: "GET_STATS_SUCCESS"
}

export default types;